# VictoriaMetrics 配置
victoria_metrics:
  address: "http://192.168.50.2:8428"
  timeout: 30s

# 报告配置
report:
  output_dir: "./reports"
  format: "xlsx"

# 默认标签配置
labels:
  - "env=home"
  - "region=home"
  - "source=categraf"

# 并发配置
concurrency: 5
